services:
    reverse-proxy:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./nginx.crt:/etc/nginx/nginx.crt
            - ./nginx.key:/etc/nginx/nginx.key
        ports:
            - 443:443
    postgres:
        image: postgres:10
        environment:
            POSTGRES_DB: guillotina
            POSTGRES_USER: guillotina
            POSTGRES_PASSWORD: secret
    abfab:
        image: ebrehault/abfab:latest
        conatiner_name: abfab
        command: sh -c "sleep 5 && guillotina"
        volumes:
            - ./config.yaml:/app/config.yaml
        ports:
            - 8080:8080
        links:
            - postgres
    abfab-utils:
        image: ebrehault/abfab-utils:latest
        command: sh utils/init.sh
        links:
            - postgres
            - abfab
