services:
    reverse-proxy:
        image: nginx
        volumes:
            - ./nginx-local.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
        links:
            - abfab
    postgres:
        image: postgres:10
        environment:
            POSTGRES_DB: guillotina
            POSTGRES_USER: guillotina
            POSTGRES_PASSWORD: my-secret
    abfab:
        container_name: abfab
        build:
            context: ../server/abfab
            dockerfile: Dockerfile
        command: sh -c 'sleep 5 && guillotina --override="root_user.password=root" --override="databases.db.dsn=postgresql://guillotina:my-secret@postgres:5432/guillotina"'
        ports:
            - 8080:8080
        volumes:
            - ./config.yaml:/app/config.yaml
        links:
            - postgres
    abfab-utils:
        build:
            context: ..
            dockerfile: docker/Dockerfile-utils
        command: sh utils/init.sh abfab root
        links:
            - postgres
            - abfab
