services:
    reverse-proxy:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./nginx.crt:/etc/nginx/nginx.crt
            - ./nginx.key:/etc/nginx/nginx.key
        ports:
            - 443:443
    postgres:
        image: postgres:10
        environment:
            POSTGRES_DB: guillotina
            POSTGRES_USER: guillotina
            POSTGRES_PASSWORD: guillotina
    abfab:
        build:
            context: ../server/abfab
            dockerfile: Dockerfile
        command: sh -c "sleep 5 && guillotina"
        ports:
            - 8080:8080
        links:
            - postgres
    abfab-utils:
        build:
            context: ..
            dockerfile: docker/Dockerfile-utils
        command: sh utils/init.sh
        links:
            - postgres
            - abfab
