services:
    reverse-proxy:
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt/live/<your-domain>:/ssl
        ports:
            - 443:443
        depends_on:
            - abfab
            - abfab-utils
    postgres:
        image: postgres:10-alpine
        environment:
            POSTGRES_DB: guillotina
            POSTGRES_USER: guillotina
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    abfab:
        image: ebrehault/abfab:latest
        container_name: abfab
        command: sh -c 'sleep 5 && guillotina --override="root_user.password=${PASSWORD}" --override="jwt.secret=${JWT_SECRET}" --override="databases.db.dsn=postgresql://guillotina:${POSTGRES_PASSWORD}@postgres:5432/guillotina"'
        volumes:
            - ./config.yaml:/app/config.yaml
        depends_on:
            - postgres
    abfab-utils:
        container_name: abfab-utils
        image: ebrehault/abfab-utils:latest
        command: sh utils/init.sh abfab ${PASSWORD}
        volumes:
            - ./src:/app/src
            - .env:/app/utils/.env
        depends_on:
            - postgres
            - abfab
