name: CI
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.9'
            - name: Install
              run: |
                  cd server/abfab && pip install -e .[test]
            - name: Run test suite
              run: |
                  cd server/abfab && pytest ./abfab
